### ISSUE TITLE
Use longer Wordlist

### ISSUE THREAD

**Issue by Don42** [dbrgn/xkcdpass-rs#5]
The original Python implementation has a 65k word list that could be used [0].
This would obviously increase the word combinations from 9003^4 to 65000^4, 
though I am not sure how to calculate that entropy bit count.

[0] [xkcdpass default list](https://github.com/redacted/XKCD-password-generator/blob/master/xkcdpass/static/default.txt)

**Comment by dbrgn** [comment]
The words are much harder to remember though and include captalization and special characters. If you have to think three times until you can properly spell Alpheratz, Arkhangelsk or Agamemnon then all the advantages of having memorable words are gone.

If I'm going to switch the default wordlist, then it'll probably be the one mentioned in #2. Otherwise, people will probably be able to use custom wordlists in the future, see #2.

**Comment by Don42** [comment]
I agree with the problem of capitalization and special characters, but I haven't had that problem yet. If I hit a particular difficult word, I just I regenerate a password.
When switching the default list you might as well merge your list with the one from EFF, which would get the list to 15693 words.
